---
title: "Deployment on Forecasted Input"
author: "TJ Sipin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, eval=T}
knitr::opts_chunk$set(echo = T, 
                      cache = F, 
                      eval = T, 
                      results = 'show',
                      warning = F,
                      message = F)

```

This report gives five different stacked models to predict cutaneous leishmaniasis using data from 2000 to 2013, with each model differing by threshold determining what constitutes low levels and high levels of cutaneous leishmaniasis.

## Seed, Packages, and Data Set

```{r, eval=T}
set.seed(123)
library(readr)
library(tidyverse)
library(tidymodels)
library(stacks)
library(dplyr)
library(caret)
library(kernlab)

# load model
load('model_stacks/FINAL_model_st_later_CL_classif_40')
load('data_tests/FINAL_data_test_later_CL_classif_40')
aad <- read_csv('../../models/data/aad.csv')
monthly <- read_csv('../../data/monthly_df.csv')
```

```{r}
load('../../extrapolation/projected_input_1m')
load('../../extrapolation/projected_input_12m')
load('../../extrapolation/projected_input_24m')
load('../../extrapolation/projected_input_36m')
load('../../extrapolation/projected_input_48m')
load('../../extrapolation/projected_input_60m')
load('../../extrapolation/complete_projected')
complete <- test_rwf_df_9 %>% 
  mutate(Population = as.integer(Population))

data <- rbind(test_rwf_df_12, test_rwf_df_24,
              test_rwf_df_36, test_rwf_df_48,
              test_rwf_df_60) %>% 
  mutate(Population = as.integer(Population))

data_res_no_month <- data %>% 
  bind_cols(predict(model_st_40,.)) %>% 
  rename(Cutaneous.Leishmaniasis = .pred_class) %>% 
  select(-c(Month))


data_res <- complete %>% 
  as.data.frame() %>% 
  select(c(-Name)) %>% 
  bind_cols(predict(model_st_40,.)) %>% 
  rename(Cutaneous.Leishmaniasis = .pred_class)


# Set up aad to check
aad_new <- aad %>% 
  filter(Cutaneous.Leishmaniasis > 0) %>% 
  filter(!is.na(Cutaneous.Leishmaniasis)) %>% 
  filter(!is.na(LST_Day)) %>% 
  filter(!is.na(AvgRad)) %>% 
  filter(!is.na(SWOccurrence)) %>% 
  mutate(Cutaneous.Leishmaniasis = ifelse(
    Cutaneous.Leishmaniasis < quantile(Cutaneous.Leishmaniasis, 0.4), 0, 1) %>% as.numeric()) %>% 
  select(c(colnames(data_res_no_month)))

summary(aad_new)
```



```{r}
# TODO: get 2019 levels to match all other years
# remove 2019 new_aad from total_data
monthly_short <- monthly %>% 
  filter(Year > 2013) %>% 
  filter(!is.na(LST_Day)) %>% 
  filter(!is.na(AvgRad)) %>% 
  filter(!is.na(EVI)) %>% 
  filter(!is.na(NDVI)) %>% 
  filter(!is.na(Precip)) %>% 
  filter(!is.na(SWOccurrence)) %>% 
  mutate(Month = (Year - 2014)*12 + Month) %>% 
  select(c(Name, Code, Year, Month,
           Population, LST_Day,
           NDVI, EVI, Precip,
           AvgRad, SWOccurrence,
           pland_forest, area_mn_forest,
           enn_mn_forest, te_forest)) %>% 
  mutate(pland_forest = ifelse(is.na(pland_forest), 0,
                               pland_forest)) %>% 
  mutate(area_mn_forest = ifelse(is.na(area_mn_forest), 0,
                                 area_mn_forest)) %>% 
  mutate(enn_mn_forest = ifelse(is.na(enn_mn_forest), 0,
                                 enn_mn_forest)) %>% 
  mutate(te_forest = ifelse(is.na(te_forest), 0,
                            te_forest)) %>% 
  mutate(Code = sub("^0+", "", Code) %>% as.integer())

tool_2019 <- monthly_short %>% 
  filter(Year == 2019) %>% 
  group_by(Code) %>% 
  mutate(Precip = sum(Precip)) %>% 
  mutate(Population = as.numeric(Population)) %>% 
  mutate(Code = as.numeric(Code)) %>% 
  summarise_if(is.numeric, mean) %>% 
  ungroup() %>% 
  mutate(Population = as.integer(Population))

data_res_2019 <- tool_2019 %>%
  bind_cols(predict(model_st_40,.)) %>% 
  rename(Cutaneous.Leishmaniasis = .pred_class)


# Summarize by month
summary_month <- data_res %>% 
  group_by(Month) %>% 
  summarise_all(mean)

# Update 2019 for total_data
total_data_no_2019 <- rbind(data_res %>% select(c(-Month)), aad_new %>% select(c(-Name))) %>% 
  mutate(Cutaneous.Leishmaniasis = as.numeric(Cutaneous.Leishmaniasis) - 1) %>% 
  filter(Year != 2019)

total_data <- rbind(total_data_no_2019, data_res_2019 %>% select(-c(Month)))

# Summarize by year
summary_year <- total_data %>% 
  group_by(Year) %>% 
  mutate_all(as.numeric) %>% 
  summarise_all(mean) %>% 
  ungroup() %>% 
  mutate(Precip = case_when(Year < 2020 ~ Precip,
                            Year >= 2020 ~ Precip * 12)) %>% 
  mutate(Code = NULL)

summary_year
```



```{r}
monthly_short <- monthly %>% 
  filter(Year %in% c(2018, 2019)) %>% 
  group_by(Month) %>% 
  summarise_all(median)
monthly_short

pop_diff <- (monthly %>% 
    filter(Year == 2019) %>% 
    select(c(Month, Population)) %>% 
    slice(which(row_number() %% 12 == 0))) - (monthly %>%
                                       filter(Year == 2018) %>% 
                                       select(c(Month, Population)) %>% 
                                       slice(which(row_number() %% 12 == 0))) %>% 
  mutate(Month = row_number())

ggplot(pop_diff) + 
  geom_point(aes(x = Month,
                 y = Population))
```


```{r}
data <- test_rwf_df_1m %>% 
  mutate(Population = as.integer(Population))

data_res <- data %>% 
  bind_cols(predict(model_st_40,.))

aad_new %>% 
  select(c(Cutaneous.Leishmaniasis, Year)) %>% 
  group_by(Year) %>% 
  summarise(mean = mean(Cutaneous.Leishmaniasis))

table(data_res$.pred_class)

```

```{r}
load('../../extrapolation/projected_input_12m')
data <- test_rwf_df_12 %>% 
  select(c('LST_Day', 'Year', 
           'NDVI', 'EVI', 'Precip', 
           'AvgRad', 'SWOccurrence', 'pland_forest',
           'te_forest', 'enn_mn_forest','Population')) %>% 
  mutate(Population = as.integer(Population))

data_res <- data %>% 
  bind_cols(predict(model_st_40,.))

table(aad$Cutaneous.Leishmaniasis)
table(data_res$.pred_class)
```


```{r}
load('../../extrapolation/projected_input_24m')
data <- test_rwf_df_24 %>% 
  select(c('LST_Day', 'Year', 
           'NDVI', 'EVI', 'Precip', 
           'AvgRad', 'SWOccurrence', 'pland_forest',
           'te_forest', 'enn_mn_forest','Population')) %>% 
  mutate(Population = as.integer(Population))

data_res <- data %>% 
  bind_cols(predict(model_st_40,.))

table(aad$Cutaneous.Leishmaniasis)
table(data_res$.pred_class)
```

```{r}
load('../../extrapolation/projected_input_36m')
data <- test_rwf_df_36 %>% 
  select(c('LST_Day', 'Year', 
           'NDVI', 'EVI', 'Precip', 
           'AvgRad', 'SWOccurrence', 'pland_forest',
           'te_forest', 'enn_mn_forest','Population')) %>% 
  mutate(Population = as.integer(Population))

data_res <- data %>% 
  bind_cols(predict(model_st_40,.))

table(aad$Cutaneous.Leishmaniasis)
table(data_res$.pred_class)
```

```{r}
load('../../extrapolation/projected_input_48m')
data <- test_rwf_df_48 %>% 
  select(c('LST_Day', 'Year', 
           'NDVI', 'EVI', 'Precip', 
           'AvgRad', 'SWOccurrence', 'pland_forest',
           'te_forest', 'enn_mn_forest','Population')) %>% 
  mutate(Population = as.integer(Population))

data_res <- data %>% 
  bind_cols(predict(model_st_40,.))

table(aad$Cutaneous.Leishmaniasis)
table(data_res$.pred_class)
```


```{r}
load('../../extrapolation/projected_input_60m')
data <- test_rwf_df_60 %>% 
  select(c('LST_Day', 'Year', 
           'NDVI', 'EVI', 'Precip', 
           'AvgRad', 'SWOccurrence', 'pland_forest',
           'te_forest', 'enn_mn_forest','Population')) %>% 
  mutate(Population = as.integer(Population))

data_res <- data %>% 
  bind_cols(predict(model_st_40,.))

table(aad$Cutaneous.Leishmaniasis)
table(data_res$.pred_class)
```

```{r}
load('../../extrapolation/test_rwf_df_deploy')
data <- test_rwf_df_deploy %>% 
  select(c('LST_Day', 'Year', 
           'NDVI', 'EVI', 'Precip', 
           'AvgRad', 'SWOccurrence', 'pland_forest',
           'te_forest', 'enn_mn_forest','Population')) %>% 
  mutate(Population = as.integer(Population))

data_res <- data %>% 
  bind_cols(predict(model_st_40,.)) %>% 
  bind_cols(Month = test_rwf_df_deploy$Month)

ggplot(data_res) + 
  geom_point(aes(x = log(Population),
                 y = Month,
                 color = .pred_class))
```

```{r}
library(reshape2)
data_res <- data_res %>% 
  mutate(.pred_class = .pred_class %>% as.numeric()) %>% 
  mutate(Population = Population %>% as.numeric())
cormat <- round(cor(data_res), 2)
melted_cormat <- melt(cormat)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile() +
  scale_fill_gradient2(low = 'blue',
                       high = 'red',
                       mid = 'white') +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))

```


```{r 40th percentile, , echo=F}
# helper packages
library(tidyverse)
library(tidymodels)
library(stacks)


# load and split the early data using imputed data
load('../../data/imp')

aad <- read.csv('../data/aad.csv')


quantile_data <- data %>% 
  filter(!is.na(Cutaneous.Leishmaniasis)) %>% 
  filter(Cutaneous.Leishmaniasis > 0) %>% 
  dplyr::select(Cutaneous.Leishmaniasis)

quantile <- (quantile_data$Cutaneous.Leishmaniasis %>% 
  quantile(0.4))[[1]] # PARAMETER

data <- data %>%
  filter(Year >= 2014) %>%
  filter(!is.na(Cutaneous.Leishmaniasis)) %>% 
  filter(Cutaneous.Leishmaniasis > 0) %>%
  dplyr::select(c('Cutaneous.Leishmaniasis', 'LST_Day', 'Year', # include LST_Night?
                  'NDVI', 'EVI', 'Precip', 
                  'AvgRad', 'SWOccurrence', 'pland_forest',
                  'te_forest', 'enn_mn_forest','Population'))


data$pland_forest <- ifelse(is.na(data$pland_forest), 0, data$pland_forest)
data$te_forest <- ifelse(is.na(data$te_forest), 0, data$te_forest)
data$enn_mn_forest <- ifelse(is.na(data$enn_mn_forest), 0, data$enn_mn_forest)

data$Cutaneous.Leishmaniasis <- as.factor(ifelse(data$Cutaneous.Leishmaniasis < quantile, 0, 1))

set.seed(123) # for reproducibility
aad <- aad %>% 
  filter(Year >= 2014) %>%
  filter(!is.na(Cutaneous.Leishmaniasis)) %>% 
  filter(Cutaneous.Leishmaniasis > 0) 

split <- initial_split(data)

data_train <- training(split)
data_test_40_temp <- testing(split)

data_test_40 <-  (aad %>% 
                    select(c(colnames(data_test_40_temp))))[Index_temp,] %>% 
  subset(!is.na(LST_Day)) %>% 
  subset(!is.na(SWOccurrence))


data_test_40$pland_forest <- ifelse(is.na(data_test_40$pland_forest), 0, data_test_40$pland_forest)
data_test_40$te_forest <- ifelse(is.na(data_test_40$te_forest), 0, data_test_40$te_forest)
data_test_40$enn_mn_forest <- ifelse(is.na(data_test_40$enn_mn_forest), 0, data_test_40$enn_mn_forest)

data_test_40$Cutaneous.Leishmaniasis <- as.factor(ifelse(data_test_40$Cutaneous.Leishmaniasis < quantile, 0, 1))

# use a 5-fold cross-validation
folds <- rsample::vfold_cv(data_train, 
                           v = 5, 
                           strata = Cutaneous.Leishmaniasis)

# set up a basic recipe
data_rec <-
  recipe(Cutaneous.Leishmaniasis ~ LST_Day + Year + NDVI + 
           EVI + Precip + AvgRad + SWOccurrence + pland_forest + 
           te_forest + enn_mn_forest + Population, data = data_train) %>%
  step_dummy(all_nominal() - all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_numeric())

# define a minimal workflow
data_wflow <-
  workflow() %>% 
  add_recipe(data_rec)

# add metric
metric <- metric_set(sensitivity, accuracy)

# save assessment set predictions and workflow used to fit the resamples
ctrl_grid <- control_stack_grid()
ctrl_res <- control_stack_resamples()

# models: SVM, XGBoost, RF
## models to try: logistic regression 

# toy model
log_reg_spec <-
  logistic_reg() %>%
  set_engine('glm')

log_reg_wflow <- 
  data_wflow %>%
  add_model(log_reg_spec)

set.seed(123)
log_reg_res <-
  fit_resamples(
    log_reg_wflow,
    resamples = folds,
    metrics = metric,
    control = ctrl_res
  )

# define svm model using parsnip
svm_spec <- 
  svm_rbf(
    cost = parsnip::tune(),
    rbf_sigma = parsnip::tune(),
    engine = 'kernlab',
    mode = 'classification'
  ) 

# add it to a workflow
svm_wflow <- 
  data_wflow %>% 
  add_model(svm_spec)

# tune cost and rbf_sigma and fit to the 5-fold cv
set.seed(123)
svm_res <-
  tune_grid(
    svm_wflow,
    resamples = folds,
    grid = 5,
    control = ctrl_grid
  )

save(svm_res, file = 'base_models/TEMP_svm_res_later_CL_classif_40')

# define xgboost model using parsnip

set.seed(123)
xgb_spec <- 
  boost_tree(
    mtry = tune(),
    trees = tune(),
    min_n = tune(),
    tree_depth = tune(),
    learn_rate = tune(),
    loss_reduction = tune()
  ) %>% 
  set_engine('xgboost') %>% 
  set_mode('classification')

# add it to a workflow
xgb_wflow <- 
  data_wflow %>%
  add_model(xgb_spec)

# tune mtry, trees, min_n, tree_depth, etc.
xgb_res <-
  tune_grid(
    xgb_wflow,
    resamples = folds,
    grid = 5,
    control = ctrl_grid
  )

save(xgb_res, file = 'base_models/TEMP_xgb_res_later_CL_classif_40')
# 

# define rf model using parsnip

set.seed(123)
rf_spec <- 
  rand_forest(
    mtry = tune(),
    trees = tune(),
    min_n = tune()
  ) %>% 
  set_engine('ranger') %>% 
  set_mode('classification')

# add it to a workflow
rf_wflow <- 
  data_wflow %>%
  add_model(rf_spec)

# tune mtry, trees, min_n
rf_res <-
  tune_grid(
    rf_wflow,
    resamples = folds,
    grid = 5,
    control = ctrl_grid
  )


save(rf_res, file = 'base_models/TEMP_rf_res_later_CL_classif_40')
# 


library(discrim) # for engine = 'naivebayes' or 'klaR'
library(agua) # for engine = 'h2o'

# define nb model using parsnip
nb_spec <- 
  naive_Bayes(
    mode = 'classification',
    smoothness = tune(),
    Laplace = tune(),
    engine = 'naivebayes'
  )



# add it to a workflow
nb_wflow <- 
  data_wflow %>%
  add_model(nb_spec)

# tune smoothness and Laplace
nb_res <-
  tune_grid(
    nb_wflow,
    resamples = folds,
    grid = 5,
    control = ctrl_grid
  )

save(nb_res, file = 'base_models/TEMP_nb_res_later_CL_classif_40')

load(file = 'base_models/TEMP_svm_res_later_CL_classif_40')
load(file = 'base_models/TEMP_xgb_res_later_CL_classif_40')
load(file = 'base_models/TEMP_rf_res_later_CL_classif_40')
load(file = 'base_models/TEMP_nb_res_later_CL_classif_40')


data_st_40 <- 
  stacks() %>% 
  add_candidates(xgb_res) %>% 
  add_candidates(rf_res) %>% 
  add_candidates(svm_res) %>% 
  add_candidates(nb_res)


save(data_st_40, file = 'data_stacks/TEMP_data_st_later_CL_classif_40')
load('data_stacks/TEMP_data_st_later_CL_classif_40')

# creating a model stack
## ready to evaluate how it is that we need to combine predictions from
## each candidate ensembe member

model_st_40 <-
  data_st_40 %>% 
  blend_predictions()

model_st_40 <-
  model_st_40 %>% 
  fit_members()

save(model_st_40, file = 'model_stacks/TEMP_model_st_later_CL_classif_40')

load('model_stacks/TEMP_model_st_later_CL_classif_40')

data_test_40 <-
  data_test_40 %>%
  bind_cols(predict(model_st_40, .))

save(data_test_40, file = 'data_tests/TEMP_data_test_later_CL_classif_40')
load('data_tests/TEMP_data_test_later_CL_classif_40')


# confusion matrix for stacks
conf_mat_later_CL_classif_40 <- caret::confusionMatrix(data = data_test_40$.pred_class, 
                                                       reference = data_test_40$Cutaneous.Leishmaniasis,
                                                       positive = '1')

save(conf_mat_later_CL_classif_40, file = 'confusion_matrices/TEMP_conf_mat_later_CL_classif_40')

# confusion matrix for base models

member_preds <- 
  data_test_40 %>% 
  dplyr::select(Cutaneous.Leishmaniasis) %>% 
  bind_cols(
    predict(
      model_st_40,
      data_test_40,
      members = TRUE
    )
  )

```

# Appendix: All code for this report

```{r ref.label=knitr::all_labels(), echo=TRUE, ALSE}
```