---
title: "R Notebook"
output: html_notebook
---

# Read in original data

```{r}
library(PRROC) # ROC curves in data frames
library(tidyverse) # everything
library(visdat) # missingness plots
library(doParallel) # parallel missForest
library(doRNG) # reproducible parallel results
library(gridExtra) # combining graphs
library(randomForest) # random forests
library(missForest) # ...
library(kableExtra) # pretty tables
library(ggplot2)
library(ggfortify)
library(forecast)

theme_set(theme_light()) # ggplot theme

aad <- read_csv('../models/data/aad.csv')
load('../data/imp')

```

# Prepare predictors for training

```{r}
later <- aad %>%
  filter(Year > 2013) %>% 
  filter(!is.na(Cutaneous.Leishmaniasis)) %>% 
  filter(Cutaneous.Leishmaniasis > 0) %>%
  dplyr::select(c('Year', 'LST_Day', # include LST_Night?
                  'NDVI', 'EVI', 'Precip', 
                  'AvgRad', 'SWOccurrence', 'pland_forest',
                  'te_forest', 'enn_mn_forest','Population')) %>% 
  subset(!is.na(LST_Day)) %>%
  subset(!is.na(SWOccurrence)) 

later$pland_forest <- ifelse(is.na(later$pland_forest), 0, later$pland_forest)
later$te_forest <- ifelse(is.na(later$te_forest), 0, later$te_forest)
later$enn_mn_forest <- ifelse(is.na(later$enn_mn_forest), 0, later$enn_mn_forest)

train_index <- sample(nrow(later), nrow(later) * 0.7)
train <- later[train_index, ]
train_X <- prodNA(train %>% 
                    select(-Year), 0.2)

test <- later[-train_index, ]
test_X <- prodNA(test %>% 
                   select(-Year), 0.2)
vis_miss(rbind(train_X, test_X),
         show_perc = T) + 
  coord_flip()

later %>% dim
```


```{r}
doParallel::registerDoParallel(cores = 4) # set based on number of CPU cores
doRNG::registerDoRNG(seed = 123)
# v1
missForest_v1 <- missForest(as.data.frame(train_X), 
                    xtrue = as.data.frame(later),
                    variablewise = T,
                    maxiter = 3, 
                    mtry = 9, 
                    ntree = 1000,
                    parallelize = 'forests')


# v2
missForest_v2 <- missForest(as.data.frame(train_X), 
                    xtrue = as.data.frame(later),
                    variablewise = T,
                    parallelize = 'forests')


# MSE
data.frame(varname = 
             names(missForest_v1$ximp), 
           error_type = 
             names(missForest_v1$OOBerror), 
           error = 
             missForest_v1$OOBerror) %>%
  mutate(error_type = cell_spec(error_type, 
                                color = "white",
                                background = "deepskyblue")) %>%
  kable(escape = F) %>% 
  kable_styling(full_width = F)

data.frame(varname = 
             names(missForest_v2$ximp), 
           error_type = 
             names(missForest_v2$OOBerror), 
           error = 
             missForest_v2$OOBerror) %>%
  mutate(error_type = cell_spec(error_type, 
                                color = "white",
                                background = "deepskyblue")) %>%
  kable(escape = F) %>% 
  kable_styling(full_width = F)


missForest_v1$error; missForest_v2$error
```

# Time Series stuff

### Toy data frame

```{r}
test_aad <- aad %>% 
  filter(Code == 5001) %>% 
  select(c(Year, LST_Day, # include LST_Night?
                  NDVI, EVI, Precip, 
                  AvgRad, SWOccurrence, pland_forest,
                  te_forest, enn_mn_forest,Population))

test_data <- data %>% 
  filter(Code == 5001) %>% 
  select(c(Code,Year, LST_Day, # include LST_Night?
           NDVI, EVI, Precip, 
           AvgRad, SWOccurrence, pland_forest,
           te_forest, enn_mn_forest,Population))

data_1 <- data %>% 
  select(c(Code,Year, Population,
           LST_Day, # include LST_Night?
           NDVI, EVI, Precip, 
           AvgRad, SWOccurrence, pland_forest,
           te_forest, enn_mn_forest)) %>% 
  mutate(pland_forest = ifelse(is.na(data$pland_forest), 
                               0, data$pland_forest)) %>% 
  mutate(te_forest = ifelse(is.na(data$te_forest), 
                            0, data$te_forest)) %>% 
  mutate(enn_mn_forest = ifelse(is.na(data$enn_mn_forest),
                                0, data$enn_mn_forest))
```

### Turn into a `ts` object

```{r}
y <- ts(test_aad, start = 2000)

for(i in colnames(test_aad)) {
  (autoplot(test_aad %>% 
             select(i) %>% 
             ts(start = 2000)) +
     ggtitle(str_interp('${i}')) +
     xlab('Year')) %>% 
    print()
}
```

```{r}
ts_plotter <- function(df){
  for(i in df$Code %>% unique()){
    print(data_1 %>% 
            filter(Code == i))
    for(j in colnames(df %>% select(-c(Year, Code)))){
      (autoplot(df %>% 
                  select(j) %>% 
                  ts(start = 2000)) +
         ggtitle(str_interp('${i}: ${j}')) +
         xlab('Year')) %>% print()
    }
  } 
}

ts_plotter(data_1 %>% 
             filter(Code == c(40313, 10609)))

ts_plotter_2 <- function(df){
  for(i in 1:length(df$Code %>% unique())){
    print(df %>% 
            filter(Code == (df$Code %>% unique())[i]))
    for(j in 1:length(colnames(df %>% select(-c(Year, Code))))){
      (forecast::autoplot(df %>% 
                  filter(Code == (df$Code %>% unique())[i]) %>% 
         select(
           (colnames(df %>% 
                       select(-c(Year, Code))
           ))[j]) %>% 
         ts(start = 2000), facets=T)  +
        ggtitle(str_interp('${i}: ${j}')) +
        xlab('Year')) %>% print()
    }
  } 
}

ts_plotter_2(test_data)

ts_plotter_3 <- function(df){
  for(i in 1:length(df$Code %>% unique())){
    print(df %>% 
            filter(Code == (df$Code %>% unique())[i]))
    (forecast::autoplot(df %>% 
                          filter(Code == (df$Code %>% unique())[i]) %>% 
                          select(-c(Code,Year)) %>% 
                          ts(start = 2000), facets=T)  +
        ggtitle(str_interp('${i}')) +
        xlab('Year')) %>% print()
  } 
}

ts_plotter_3(data_1 %>% filter(Code == c(10608, 10609)))
```


```{r}
lst_lag_1 <- window((test_data %>% ts(start = 2000))[, 'LST_Day'], start = 2000) 
lst_lag_1 %>% gglagplot()
lst_lag_1 %>% autoplot()
ggAcf(lst_lag_1)
```

# RWF (FOCUS)

```{r}
fc <- rwf(test_data_y[,'LST_Day'], drift=T, lambda=0, h=50, level=80)
fc2 <- rwf(test_data_y[,'LST_Day'], drift=T, lambda=0, h=50, level=80,
           biasadj=T)
autoplot(test_data_y[,'LST_Day']) + 
  autolayer(fc, series='Simple back transformation') +
  autolayer(fc2, series='Bias adjusted', PI=F) +
  guides(color=guide_legend(title='Forecast'))

res <- residuals(fc)

autoplot(res) + 
  xlab('Year')

res2 <- residuals(fc2)

autoplot(res2) + 
  xlab('Year')

rwf(test_data_y[,'EVI'], drift=T, lambda=0, h=50, level=80)
rwf(test_data_y[,'EVI'], drift=T, lambda=0, h=50, level=80, bootstrap=T)

rwf_df <- data.frame()

for (i in unique(data_1[,'Code'])){
  for (j in colnames(data_1 %>% 
                     filter(Code == i) %>% 
                     select(-c(Code, Year)))) {
    rwf((data_1 %>% 
           filter(Code == i) %>% 
           select(c(j)) %>% ts()), 
        drift=T,
        lambda=0,
        h=10,
        level=80)
  }
}
```


```{r}
test_data_y <- data %>% 
  filter(Code == 10609) %>% 
  ts(start = 2000)
rwf(test_data_y, h = 20, drift = T)
```

