# THIS IS THE RIGHT ONE

```{r}
library(dplyr)
library(forecast)
library(ggplot2)
library(seasonal)
library(urca)
library(tidyverse)
library(progress) 

monthly <- read_csv('https://drive.google.com/file/d/1o4S9_WvzBMtXz4Y3VXF3bxm1oTryQefX/view?usp=sharing')
```

# Set up `monthly_short`

```{r}
monthly_short <- monthly %>% 
  filter(Year > 2013) %>% 
  filter(!is.na(LST_Day)) %>% 
  filter(!is.na(AvgRad)) %>% 
  filter(!is.na(EVI)) %>% 
  filter(!is.na(NDVI)) %>% 
  filter(!is.na(Precip)) %>% 
  filter(!is.na(SWOccurrence)) %>% 
  mutate(Month = (Year - 2014)*12 + Month) %>% 
  select(c(Name, Code, Year, Month,
           Population, LST_Day,
           NDVI, EVI, Precip,
           AvgRad, SWOccurrence,
           pland_forest, area_mn_forest,
           enn_mn_forest, te_forest)) %>% 
  mutate(pland_forest = ifelse(is.na(pland_forest), 0,
                               pland_forest)) %>% 
  mutate(area_mn_forest = ifelse(is.na(area_mn_forest), 0,
                                 area_mn_forest)) %>% 
  mutate(te_forest = ifelse(is.na(te_forest), 0,
                            te_forest)) %>% 
  mutate(Code = sub("^0+", "", Code) %>% as.integer())

monthly_short %>% summary
```

```{r}
monthly_short_ts <- monthly_short %>% ts(start = 1)

# forecast
monthly_short %>% 
  filter(monthly_short$Code == 10101) %>% 
  select(LST_Day) %>% 
  ts(start = 1) %>% 
  window(start = 1) %>% 
  rwf(h = 60,
      drift = T)

# autoplot
monthly_short %>% 
  filter(monthly_short$Code == 10101) %>% 
  select(LST_Day) %>% 
  ts(start = 1) -> monthly_short_10101_LST

# autoplot 2

autoplot(monthly_short_10101_LST, series="Data") + 
  autolayer(ma(monthly_short_10101_LST, 6), series="6-MA") +
  scale_color_manual(values=c("Data"="grey", "6-MA"="red"),
                     breaks=c("Data","6-MA"))

monthly_short_10101_LST %>% ur.kpss() %>% summary()
```

```{r}
monthly_adj <- monthly_short %>% 
  select(c(Month, LST_Day)) %>% 
  stl(s.window = 'periodic') %>% 
  seasadj()

```


```{r}
aad <- read_csv('../models/data/aad.csv')
```

```{r}
aad_short <- aad %>% 
  filter(Year > 2013) %>% 
  filter(!is.na(LST_Day)) %>% 
  filter(!is.na(AvgRad)) %>% 
  filter(!is.na(EVI)) %>% 
  filter(!is.na(NDVI)) %>% 
  filter(!is.na(Precip)) %>% 
  filter(!is.na(SWOccurrence)) %>% 
  select(c(Name, Code, Year,
           Population, LST_Day,
           NDVI, EVI, Precip,
           AvgRad, SWOccurrence,
           pland_forest, area_mn_forest,
           te_forest)) %>% 
  mutate(pland_forest = ifelse(is.na(pland_forest), 0,
                               pland_forest)) %>% 
  mutate(area_mn_forest = ifelse(is.na(area_mn_forest), 0,
                                 area_mn_forest)) %>% 
  mutate(te_forest = ifelse(is.na(te_forest), 0,
                            te_forest))

```


```{r}
h = 24 # param


test_rwf_df_4 <- data.frame(matrix(ncol = ncol(monthly_short),
                            nrow = 0))

for (i in 1:(unique(monthly_short[,'Code']) %>% nrow)){ # 1:8266
  for(j in 1:h) { # 1:10
    for (k in 5:(colnames(monthly_short) %>% length)) { # 3:14
      skip <- FALSE
      
      test_rwf_df_4[(i-1)*h + j, k] = rwf(monthly_short %>% 
                                            filter(Code == unique(monthly_short[,'Code'])[i,1]) %>% 
                                            select(c(colnames(monthly_short)[k])) %>%
                                            ts(start = 1), 
                                          na.rm = TRUE,
                                          lambda='auto',
                                          h=h,
                                          level=80,
                                          drift=T,
                                          bootstrap=T)$mean[j] %>% 
        tryCatch(error = function(e){ skip <- TRUE })
      if(skip) {
        test_rwf_df_4[(i-1)*h + j, k] = rwf(monthly_short %>% 
                                            filter(Code == unique(monthly_short[,'Code'])[i,1]) %>% 
                                            select(c(colnames(monthly_short)[k])) %>%
                                            ts(start = 1), 
                                          na.rm = TRUE,
                                          lambda='auto',
                                          h=h,
                                          level=80,
                                          drift=F,
                                          bootstrap=T)$mean[j]
      }

    }
    test_rwf_df_4[(i-1)*h + j, 1] = unique(monthly_short[,'Name'])[1,i]
    test_rwf_df_4[(i-1)*h + j, 2] = unique(monthly_short[,'Code'])[1,i]
    test_rwf_df_4[(i-1)*h + j, 3] = 2020 + floor(j/12)
    test_rwf_df_4[(i-1)*h + j, 4] = j %% 12
    
    
  }
}


```

```{r}

fit <- auto.arima((aad_short %>% filter(Code == sample(aad_short$Code %>% unique(), 1)))[,'Precip'], seasonal=T)
fit %>% forecast(h=60) %>% autoplot(include=80)

```


```{r}
set.seed(122123)
# Toy
fit <- auto.arima((monthly_short %>% filter(Code == sample(monthly_short$Code %>% unique(), 1)))[,'LST_Day'], 
                  seasonal=T, 
                  D = 1,
                  biasadj = T,
                  allowdrift = T,
                  lambda = 'auto')
fit %>% forecast(h=120) %>% autoplot(include=80)
```

```{r}
h = 60 # param


test_rwf_df_5 <- data.frame(matrix(ncol = ncol(monthly_short),
                            nrow = 0))

for (i in 1:(unique(monthly_short[,'Code']) %>% nrow)){ # 1:8266
  for(j in 1:h) { # 1:10
    for (k in 5:(colnames(monthly_short) %>% length)) { # 5:14
      
      test_rwf_df_5[(i-1)*h + j, k] = (auto.arima(monthly_short %>% 
                                            filter(Code == (unique(monthly_short[,'Code'])[i,] %>% as.integer())) %>% 
                                            select(c(colnames(monthly_short)[k])), 
                                          seasonal = T) %>% 
                                         forecast(h = h))$mean[j]
    }
    test_rwf_df_5[(i-1)*h + j, 1] = unique(monthly_short[,'Name'])[i,]
    test_rwf_df_5[(i-1)*h + j, 2] = unique(monthly_short[,'Code'])[i,]
    test_rwf_df_5[(i-1)*h + j, 3] = 2020 + floor(j/12)
    test_rwf_df_5[(i-1)*h + j, 4] = j %% 12
  }
}

colnames(test_rwf_df_5) <- monthly_short %>% colnames



pb <- progress_bar$new(format = '(:spin) [:bar] :percent [Elapsed time: :elapsedfull || Estimated time remaining: :eta]',
                       total = unique(monthly_short_2[,'Code']) %>% nrow,
                       complete = '=',
                       incomplete = '-',
                       current = '>',
                       clear = F,
                       width = 100)




for (i in 1:(unique(monthly_short_2[,'Code']) %>% nrow)){
  pb$tick()
  for (j in 1:h){
      test_rwf_df_8[(i-1)*h + j, 3] = (auto.arima(monthly_short_2 %>% 
                                                    filter(Code == (unique(monthly_short_2[,'Code'])[i,] %>% as.integer())) %>% 
                                                    select(c(colnames(monthly_short_2)[3])),
                                                  seasonal = T) %>% 
                                         forecast(h = h))$mean[j]
  }
}
```

```{r}
# library(doParallel)
# library(foreach)
# no_cores <- detectCores() - 1
# registerDoParallel(cores = no_cores)
# cl <- makeCluster(no_cores, type = "FORK")

# Forgot to add enn_mn_forest

monthly_short_2 <- monthly %>% 
  filter(Year > 2013) %>% 
  filter(!is.na(LST_Day)) %>% 
  filter(!is.na(AvgRad)) %>% 
  filter(!is.na(EVI)) %>% 
  filter(!is.na(NDVI)) %>% 
  filter(!is.na(Precip)) %>% 
  filter(!is.na(SWOccurrence)) %>% 
  mutate(Month = (Year - 2014)*12 + Month) %>% 
  select(c(Code, Month, enn_mn_forest)) %>% 
  mutate(enn_mn_forest = ifelse(is.na(enn_mn_forest), 0,
                                enn_mn_forest)) %>%  # try a version removing all NAs 
  mutate(Code = sub("^0+", "", Code) %>% as.integer())

pb <- progress_bar$new(format = '(:spin) [:bar] :percent [Elapsed time: :elapsedfull || Estimated time remaining: :eta]',
                       total = unique(monthly_short_2[,'Code']) %>% nrow,
                       complete = '=',
                       incomplete = '-',
                       current = '>',
                       clear = F,
                       width = 100)

load('test_rwf_df_5')
h = 60 # param
test_rwf_df_8 <- test_rwf_df_5


# foreach(i = 1:(unique(monthly_short_2[,'Code']) %>% nrow())) %dopar% {
#   pb$tick()
#   foreach(j = 1:h) %dopar% {
#     test_rwf_df_8[(i-1)*h + j, 3] = (auto.arima(monthly_short_2 %>% 
#                                                     filter(Code == (unique(monthly_short_2[,'Code'])[i,] %>% as.integer())) %>% 
#                                                     select(c(colnames(monthly_short_2)[3])),
#                                                   seasonal = T) %>% 
#                                          forecast(h = h))$mean[j]
#   }
# }

for (i in 1:(unique(monthly_short_2[,'Code']) %>% nrow)){
  pb$tick()
  for (j in 1:h){
      test_rwf_df_8[(i-1)*h + j, 3] = (auto.arima(monthly_short_2 %>% 
                                                    filter(Code == (unique(monthly_short_2[,'Code'])[i,] %>% as.integer())) %>% 
                                                    select(c(colnames(monthly_short_2)[3])),
                                                  seasonal = T) %>% 
                                         forecast(h = h))$mean[j]
  }
}

# save(test_rwf_df_8, file = 'test_rwf_df_8')
load(file = 'test_rwf_df_8')


test_rwf_df_8 %>% 
  select(c(Year, area_mn_forest, te_forest, pland_forest)) %>% 
  summary()

aad %>% 
  filter(!is.na(Cutaneous.Leishmaniasis)) %>% 
  filter(Cutaneous.Leishmaniasis > 0) %>% 
  select(c(enn_mn_forest, area_mn_forest, te_forest, pland_forest)) %>% 
  summary()
```



```{r}
library(reshape)
graph_df <- monthly_short %>%
  mutate(Month = (Year - 2014 + 1) + Month) %>% 
  mutate(enn_mn_forest = monthly_short_2$enn_mn_forest) %>%
  filter(Code == sample(Code, 1)) %>% 
  select(c(Month, enn_mn_forest, te_forest, pland_forest, area_mn_forest)) 

graph_df_long <- melt(graph_df,
                      id = 'Month', 
                      measure = c('enn_mn_forest',
                                  'te_forest',
                                  'pland_forest',
                                  'area_mn_forest'))

ggplot(graph_df) +
  geom_point(aes(x = Month,
                 y = enn_mn_forest))
```


```{r}
test_rwf_df_9 <- test_rwf_df_8 %>% 
  mutate(enn_mn_forest = Year) %>% 
  mutate(Year = test_rwf_df_5$Year) %>% 
  mutate(Month = Month + 1) %>% 
  mutate(Month = (Year - 2020)*12 + Month - 1) %>% 
  mutate(enn_mn_forest = enn_mn_forest - min(enn_mn_forest)) %>% 
  mutate(area_mn_forest = area_mn_forest - min(area_mn_forest)) %>%
  mutate(te_forest = te_forest - min(te_forest)) %>%
  mutate(pland_forest = pland_forest - min(pland_forest))
```

```{r}
test_rwf_df_1m <- test_rwf_df_9 %>% 
  filter(Month == 1) 

save(test_rwf_df_1m, file = 'projected_input_1m')
write.csv(test_rwf_df_1m, file = 'projectedd_input_1m.csv')

test_rwf_df_12 <- test_rwf_df_9 %>% 
  filter(Month == 12) 

save(test_rwf_df_12, file = 'projected_input_12m')
write.csv(test_rwf_df_12, file = 'projectedd_input_12m.csv')

test_rwf_df_24 <- test_rwf_df_9 %>% 
  filter(Month == 24) 

save(test_rwf_df_24, file = 'projected_input_24m')
write.csv(test_rwf_df_24, file = 'projectedd_input_24m.csv')

test_rwf_df_36 <- test_rwf_df_9 %>% 
  filter(Month == 36)

save(test_rwf_df_36, file = 'projected_input_36m')
write.csv(test_rwf_df_36, file = 'projectedd_input_36m.csv')

test_rwf_df_48 <- test_rwf_df_9 %>% 
  filter(Month == 48)

save(test_rwf_df_48, file = 'projected_input_48m')
write.csv(test_rwf_df_48, file = 'projectedd_input_48m.csv')

test_rwf_df_60 <- test_rwf_df_9 %>% 
  filter(Month == 60)

save(test_rwf_df_10, file = 'projected_input_60m')
write.csv(test_rwf_df_10, file = 'projected_input_60m.csv')
```

```{r}
test_rwf_df_12
test_rwf_df_24
test_rwf_df_36
test_rwf_df_48
test_rwf_df_60

test_rwf_df_deploy <- test_rwf_df_9 %>% 
  filter(Month %in% c(12,24,36,48,60))

save(test_rwf_df_deploy, file = 'test_rwf_df_deploy')
write.csv(test_rwf_df_deploy, file = 'test_rwf_deploy.csv')
```


```{r}
pb <- progress_bar$new(format = '(:spin) [:bar] :percent [Elapsed time: :elapsedfull || Estimated time remaining: :eta]',
                       total = 100,
                       complete = '=',
                       incomplete = '-',
                       current = '>',
                       clear = F,
                       width = 100)
for (i in 1:100) {se
  pb$tick()
  Sys.sleep(0.1)
}
```

```{r}
save(test_rwf_df_5, file = 'test_rwf_df_5')
load('test_rwf_df_5')
write.csv(test_rwf_df_5, file = 'test_rwf_df_5.csv')
read.csv('test_rwf_df_5.csv')
```



```{r}
monthly_short %>% filter(Code == unique(monthly_short[,'Code'])[i,] %>% as.integer())

unique(monthly_short[,'Code'])[1,]
unique(monthly_short[,'Name'])[1,]

auto.arima(monthly_short %>% 
             filter(Code == (unique(monthly_short[,'Code'])[i,] %>% as.integer())) %>% 
             select(c(colnames(monthly_short)[k])), 
           seasonal = T)

auto.arima(monthly_short %>% 
                                            filter(Code == (unique(monthly_short[,'Code'])[i,] %>% as.integer())) %>% 
                                            select(c(colnames(monthly_short)[k])), 
                                          seasonal = T) %>% 
        forecast(h = h)
```


