---
title: "deforestation"
author: "Lyndsey Umsted"
date: '2022-07-06'
output: html_document
---

```{r}
aad <- read.csv("data/aad.csv")
library(dplyr)
## splitting the data into a before 2014 set and an after 2014 set

early_data <- aad %>%
  filter(Year < 2014)%>%
  dplyr::select(c(1:28,30,36,40,45))
later_data <- aad %>%
  filter(Year > 2013) %>%
  dplyr::select(c(1:28,30,36,40,45))

#names(early_data)

## removing unnecessary variables

early_data <- early_data %>%
  dplyr::select(-c("AvgRad"))
later_data <- later_data %>%
  dplyr::select(-c("StableLights")) 

early_data$enn_mn_forest[is.na(early_data$enn_mn_forest)] = 0
early_data$te_forest[is.na(early_data$te_forest)] = 0
early_data$area_mn_forest[is.na(early_data$area_mn_forest)] = 0
early_data$pland_forest[is.na(early_data$pland_forest)] = 0

later_data$enn_mn_forest[is.na(later_data$enn_mn_forest)] = 0
later_data$te_forest[is.na(later_data$te_forest)] = 0
later_data$area_mn_forest[is.na(later_data$area_mn_forest)] = 0
later_data$pland_forest[is.na(later_data$pland_forest)] = 0

lapply(early_data, as.numeric)
lapply(later_data, as.numeric)

early_data_cutaneous <- subset(early_data, !is.na(early_data$Cutaneous.Leishmaniasis))
later_data_cutaneous <- subset(later_data, !is.na(later_data$Cutaneous.Leishmaniasis))
```


```{r}
later_data_small <- later_data_cutaneous %>%
  select(c("Cutaneous.Leishmaniasis", "pland_forest", "area_mn_forest", "te_forest", "enn_mn_forest")) %>%
  na.omit(later_data_small) 
```



```{r}
# splitting data into training and test data
library(rsample)
library(xgboost)
set.seed(21)
data_split <- initial_split(later_data_small, prop = 0.9, strata = Cutaneous.Leishmaniasis)
train <- training(data_split)
test <- testing(data_split)

train <- data.table(train)

# one-hot encode categorical variables
sparse_matrix <- sparse.model.matrix(
  Cutaneous.Leishmaniasis ~ . - 1, data = train
) # use for data = ?


# split training into predictors and labels
x_train <- as.matrix(train %>%
                       select(-c("Cutaneous.Leishmaniasis")))

x_train[,1:4] = as.numeric(x_train[,1:4])

y_train <- as.matrix(train %>%
                       select(Cutaneous.Leishmaniasis))

x_test <- as.matrix(test %>%
                      select(-c("Cutaneous.Leishmaniasis")))

x_test[,1:4] = as.numeric(x_test[,1:4])

y_test <- as.matrix(test %>%
                      select(Cutaneous.Leishmaniasis))

dtrain <- xgb.DMatrix(data = x_train, label = y_train)
dtest <- xgb.DMatrix(data = x_test, label = y_test)
```

```{r}
# Basic training

## Parameters
params <- list(booster = "gbtree", 
               objective = "reg:linear",
               eta = 0.3,
               gamma = 20,
               max.depth = 1, 
               min_child_weight = 2,
               subsample = 1,
               colsample_bytree = 1,
               lambda = 0
)

xgbcv <- xgb.cv(params = params,
                data = x_train, 
                label = y_train, 
                nrounds = 1000,
                nfold = 5,
                showsd = T,
                stratified = T,
                print_every_n = 10,
                early_stopping_rounds = 20,
                maximize = F,
                verbose = 2)  # eta = 1: train-rmse:0.000601 @ [41]
# eta = 0.3: train-rsme:0.001090 @ [132]
# min_child_weight = 1: 0.530765
xgbcv$best_iteration

# first default - model training
xgb1 <- xgb.train (params = params, 
                   data = dtrain, 
                   nrounds = xgbcv$best_iteration, 
                   watchlist = list(val=dtest,train=dtrain), 
                   print.every.n = 10, 
                   early.stop.round = 10, 
                   maximize = F , 
                   eval_metric = "error")
```

```{r}
# model prediction
xgbpred <- predict(xgb1, dtest)

# var imp plot
mat <- xgb.importance(feature_names = colnames(x_train),
                      model = xgb1)
xgb.plot.importance(importance_matrix = mat[1:ncol(x_train)])
```

```{r}
# Accuracy check

mse = mean((y_test - xgbpred)^2)
mae = caret::MAE(y_test, xgbpred)
rmse = caret::RMSE(y_test, xgbpred)

cat("MSE: ", mse, "MAE: ", mae, "RMSE: ", rmse)
```

```{r}
# Create tasks
#install.packages("ParamHelpers")
library(mlr)
traintask <- makeRegrTask(data = train, target = "Cutaneous.Leishmaniasis")
testtask <- makeRegrTask(data = test, target = "Cutaneous.Leishmaniasis")

# Create learner
lrn <- makeLearner("regr.xgboost", predict.type = "response")
lrn$par.vals <- list(objective = 'reg:squarederror',
                     eval_metric = 'error',
                     nrounds = 100)
```

```{r}
# Set parameter space
set.seed(2)
params <- makeParamSet(makeDiscreteParam('booster',
                                         values = c('gbtree', 'gblinear')),
                       makeIntegerParam('max_depth',
                                        lower = 1L,
                                        upper = 6L),
                       makeNumericParam('min_child_weight',
                                        lower = 0,
                                        upper = 1),
                       makeNumericParam('subsample',
                                        lower = 0,
                                        upper = 1),
                       makeNumericParam('colsample_bytree',
                                        lower = 0,
                                        upper = 1),
                       makeIntegerParam('gamma',
                                        lower = 0,
                                        upper = 1),
                       makeNumericParam('eta',
                                        lower = 0,
                                        upper = 0.1),
                       makeNumericParam('lambda',
                                        lower = 0,
                                        upper = 1))


# Set resampling strategy
rdesc <- makeResampleDesc('CV',
                          stratify = F,
                          iters = 5L)

# Search Strategy
ctrl <- makeTuneControlRandom(maxit = 20L)

# Set parallel backend
library(parallel)
library(parallelMap)
library(class)
parallelStartSocket(cpus = detectCores())

# Parameter tuning
mytune <- tuneParams(learner = lrn, 
                     task = traintask,
                     resampling = rdesc,
                     measures = getDefaultMeasure('regr'),
                     par.set = params,
                     control = ctrl,
                     show.info = T)

mytune$y

# Set hyperparameters
lrn_tune <- setHyperPars(lrn, par.vals = mytune$x)

# Train model
xgmodel <- train(learner = lrn_tune, task = traintask)

# Predict model
xgpred <- predict(xgmodel, testtask)
```

```{r}
#confusion matrix
#confusionMatrix(xgpred$data$response, xgpred$data$truth)
mytune$opt.path$env$path
```


```{r}
## Visualize y original test and y predicted data in plot
library(ggplot2)
x = 1:length(y_test)
performance_plot <- plot(x, y_test, col = "red", type = 'l') +
  lines(x, xgpred$data$response, col = "blue", type = 'l')
performance_plot

ggplot() + 
  geom_line(aes(x = (xgpred$data$id),
                y = (xgpred$data$truth)),
            color = 'red', size = 0.5) + 
  geom_line(aes(x = (xgpred$data$id),
                y = (xgpred$data$response)),
            color = 'blue', size = 0.5) + 
  labs(color = "Truth vs. Response")
ggplot() + 
  geom_line(aes(x = (xgpred$data$id),
                y = (xgpred$data$truth - xgpred$data$response)),
            color = 'dark green', size = 0.5) + 
  labs(color = "Truth vs. Response")
```

