---
title: "Later Data Malaria XGBoost"
author: "Lyndsey Umsted"
date: '2022-07-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# packages
# install.packages("drat", repos="https://cran.rstudio.com")
# drat:::addRepo("dmlc")
# install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")
# install.packages("tidyverse")
# install.packages("dpylr")
# install.packages("glmnet")
# install.packages("ranger")
# install.packages("lsr")
# install.packages("corrr")
# install.packages("tidyr")
# install.packages("car")
# install.packages("moments")
# install.packages("ggpubr")
# install.packages("BBmisc")
# install.packages("rsample")
# install.packages("recipes")
# install.packages("randomForest")
# install.packages("parsnip")
# install.packages("workflows")
# install.packages("tune")
# install.packages("dials")
# install.packages("yardstick")
# install.packages("xgboost")
# install.packages("data.table")
# install.packages("Matrix")
# install.packages("caret")
# install.packages("mlr3")
# install.packages("class")
```

```{r}
#libraries
library(tidyverse)
library(dplyr)
library(glmnet)
library(xgboost)
library(ranger)
library(lsr)
library(corrr)
library(tidyr)
library(car)
library(moments)
library(ggpubr)
library(BBmisc)
library(rsample)
library(recipes)
library(randomForest)
library(parsnip)
library(workflows)
library(tune)
library(dials)
library(yardstick)
require(xgboost)
require(data.table)
require(Matrix)
library(caret)
library(data.table)
library(mlr3)
library(class)
library(ParamHelpers)
```

Importing File into R:
```{r}
aad <- read.csv("Annual_Amazon_Data.csv")
#view(aad)

cutaneous <- aad$Cutaneous.Leishmaniasis
mucosal <- aad$Mucosal.Leishmaniasis
visceral <- aad$Visceral.Leishmaniasis
new_data <- subset(aad, !is.na(aad$Malaria))
#View(new_data)
#names(new_data)
```


Extracting Later Data and Tidying it:
```{r}
## splitting the data into a before 2014 set and an after 2014 set
library(dplyr)
early_data <- new_data %>%
  filter(Year < 2014)%>%
  dplyr::select(-c(29:69))
later_data <- new_data %>%
  filter(Year > 2013) %>%
  dplyr::select(-c(29:69))

#names(early_data)

## removing unnecessary variables

early_data <- early_data %>%
  dplyr::select(-c("AvgRad"))
later_data <- later_data %>%
  dplyr::select(-c("StableLights"))

# later_data$OptTemp_Obs <- as.numeric(later_data$OptTemp_Obs)
# later_data$Year <- as.numeric(later_data$Year)
# later_data$Population <- as.numeric(later_data$Population)

later_data_small <- later_data %>%
  dplyr::select(c("Population", "Malaria", "Dengue_Alb_OptTemp", "Dengue_Aeg_OptTemp", "Chik_Alb_OptTemp", "Chik_Aeg_OptTemp", "Zika_OptTemp", "Malaria_OptTemp", "LST_Day", "LST_Night", "OptTemp_Obs", "NDVI", "EVI", "Precip", "AvgRad", "SWOccurrence")) %>%
  na.omit(later_data_small) 
later_data_t <- lapply(later_data_small, as.numeric)
later_data_t <- as.data.frame(later_data_t)
later_data_t <- subset(later_data_t, later_data_t$Malaria > 0)
```

```{r}
library(dplyr)
# summary(later_data_small$Cutaneous.Leishmaniasis[later_data_small$Cutaneous.Leishmaniasis > 0])
# cat_df <- subset(later_data_small, later_data_small$Cutaneous.Leishmaniasis > 0)
# cat_df$Cutaneous.Leishmaniasis <- cut(later_data_small$Cutaneous.Leishmaniasis[later_data_small$Cutaneous.Leishmaniasis > 0], breaks = c(0, 0.090114445 , 0.876904527, 10^3), labels = c("low", "moderate", "high")) # 25% 75% 100%

# cat_df$label <- NA
# cat_df$label[cat_df$Cutaneous.Leishmaniasis == "low"] <- 0
# cat_df$label[cat_df$Cutaneous.Leishmaniasis == "moderate"] <- 1
# cat_df$label[cat_df$Cutaneous.Leishmaniasis == "high"] <- 2

# cat_df$Year <- as.numeric(cat_df$Year)
# cat_df$Population <- as.numeric(cat_df$Population)
# cat_df$OptTemp_Obs <- as.numeric(cat_df$OptTemp_Obs)
```

```{r}
skimr::skim(later_data_t)
round(prop.table(table(later_data_t$Malaria)), 2)
```

```{r}
# splitting data into training and test data
set.seed(21)
data_split <- initial_split(later_data_t, prop = 0.8, strata = Malaria)
train <- training(data_split)
test <- testing(data_split)

train <- data.table(train)

# one-hot encode categorical variables
sparse_matrix <- sparse.model.matrix(
  Malaria ~ . - 1, data = train
) # use for data = ?


# split training into predictors and labels
x_train <- as.matrix(train %>%
                       dplyr::select(-c("Malaria")))

x_train[,1:15] = as.numeric(x_train[,1:15])

y_train <- as.matrix(train %>%
                       dplyr::select(Malaria))

x_test <- as.matrix(test %>%
                      dplyr::select(-c("Malaria")))

x_test[,1:15] = as.numeric(x_test[,1:15])

y_test <- as.matrix(test %>%
                      dplyr::select(Malaria))

dtrain <- xgb.DMatrix(data = x_train, label = y_train)
dtest <- xgb.DMatrix(data = x_test, label = y_test)
```

```{r}
# Basic training

## Parameters
params <- list(booster = "gbtree", 
               objective = "reg:linear",
               eta = 0.3,
               gamma = 20,
               max.depth = 1, 
               min_child_weight = 2,
               subsample = 1,
               colsample_bytree = 1,
               lambda = 0
)

xgbcv <- xgb.cv(params = params,
                data = x_train, 
                label = y_train, 
                nrounds = 1000,
                nfold = 5,
                showsd = T,
                stratified = T,
                print_every_n = 10,
                early_stopping_rounds = 20,
                maximize = F,
                verbose = 2)  # eta = 1: train-rmse:0.000601 @ [41]
# eta = 0.3: train-rsme:0.001090 @ [132]
# min_child_weight = 1: 0.530765
xgbcv$best_iteration

# first default - model training
xgb1 <- xgb.train (params = params, 
                   data = dtrain, 
                   nrounds = xgbcv$best_iteration, 
                   watchlist = list(val=dtest,train=dtrain), 
                   print.every.n = 10, 
                   early.stop.round = 10, 
                   maximize = F , 
                   eval_metric = "error")
```

```{r}
# model prediction
xgbpred <- predict(xgb1, dtest)

# var imp plot
mat <- xgb.importance(feature_names = colnames(x_train),
                      model = xgb1)
xgb.plot.importance(importance_matrix = mat[1:ncol(x_train)])
```

```{r}
# Accuracy check

mse = mean((y_test - xgbpred)^2)
mae = caret::MAE(y_test, xgbpred)
rmse = caret::RMSE(y_test, xgbpred)

cat("MSE: ", mse, "MAE: ", mae, "RMSE: ", rmse)
```

```{r}
# Create tasks
traintask <- makeRegrTask(data = train, target = "Malaria")
testtask <- makeRegrTask(data = test, target = "Malaria")

# Create learner
lrn <- makeLearner("regr.xgboost", predict.type = "response")
lrn$par.vals <- list(objective = 'reg:squarederror',
                     eval_metric = 'error',
                     nrounds = 100)
```

```{r}
# Set parameter space
set.seed(2)
params <- makeParamSet(makeDiscreteParam('booster',
                                         values = c('gbtree', 'gblinear')),
                       makeIntegerParam('max_depth',
                                        lower = 1L,
                                        upper = 6L),
                       makeNumericParam('min_child_weight',
                                        lower = 0,
                                        upper = 1),
                       makeNumericParam('subsample',
                                        lower = 0,
                                        upper = 1),
                       makeNumericParam('colsample_bytree',
                                        lower = 0,
                                        upper = 1),
                       makeIntegerParam('gamma',
                                        lower = 0,
                                        upper = 1),
                       makeNumericParam('eta',
                                        lower = 0.01,
                                        upper = 0.1),
                       makeNumericParam('lambda',
                                        lower = 0,
                                        upper = 1))


# Set resampling strategy
rdesc <- makeResampleDesc('CV',
                          stratify = F,
                          iters = 5L)

# Search Strategy
ctrl <- makeTuneControlRandom(maxit = 20L)

# Set parallel backend
library(parallel)
library(parallelMap)
library(class)
parallelStartSocket(cpus = detectCores())

# Parameter tuning
mytune <- tuneParams(learner = lrn, 
                     task = traintask,
                     resampling = rdesc,
                     measures = getDefaultMeasure('regr'),
                     par.set = params,
                     control = ctrl,
                     show.info = T)

mytune$y

# Set hyperparameters
lrn_tune <- setHyperPars(lrn, par.vals = mytune$x)

# Train model
xgmodel <- train(learner = lrn_tune, task = traintask)

# Predict model
xgpred <- predict(xgmodel, testtask)
```

```{r}
#confusion matrix
#confusionMatrix(xgpred$data$response, xgpred$data$truth)
mytune$opt.path$env$path
```


```{r}
## Visualize y original test and y predicted data in plot
x = 1:length(y_test)
performance_plot <- plot(x, y_test, col = "red", type = 'l') +
  lines(x, xgpred$data$response, col = "blue", type = 'l')
performance_plot

ggplot() + 
  geom_line(aes(x = (xgpred$data$id),
                y = (xgpred$data$truth)),
            color = 'red', size = 0.5) + 
  geom_line(aes(x = (xgpred$data$id),
                y = (xgpred$data$response)),
            color = 'blue', size = 0.5) + 
  labs(color = "Truth vs. Response")
ggplot() + 
  geom_line(aes(x = (xgpred$data$id),
                y = (xgpred$data$truth - xgpred$data$response)),
            color = 'dark green', size = 0.5) + 
  labs(color = "Truth vs. Response")
```


